INSERT INTO PRODUCTO_OTAKU (NOMBRE, CATEGORIA, PRECIO, STOCK) VALUES ('Figura de Luffy Gear 5', 'Figura', 59.99, 10);
INSERT INTO PRODUCTO_OTAKU (NOMBRE, CATEGORIA, PRECIO, STOCK) VALUES ('Manga de Naruto Vol. 1', 'Manga', 9.99, 50);
INSERT INTO PRODUCTO_OTAKU (NOMBRE, CATEGORIA, PRECIO, STOCK) VALUES ('Póster de One Piece Wano Arc', 'Póster', 12.50, 25);
INSERT INTO PRODUCTO_OTAKU (NOMBRE, CATEGORIA, PRECIO, STOCK) VALUES ('Nendoroid Nezuko Kamado', 'Figura', 45.00, 7);
INSERT INTO PRODUCTO_OTAKU (NOMBRE, CATEGORIA, PRECIO, STOCK) VALUES ('Manga de Attack on Titan Vol. 1', 'Manga', 10.50, 40);
INSERT INTO PRODUCTO_OTAKU (NOMBRE, CATEGORIA, PRECIO, STOCK) VALUES ('Set de Chapas de My Hero Academia', 'Accesorio', 15.00, 30);